player_table = 'player'
op_game_data = 'offense_game_stats'
dp_game_data = 'defense_game_stats'
sp_game_data = 'special_game_stats'
game_table = 'game'
stadium_table = 'stadium'
team_table = 'team'
season_table = 'season'
