player_table = 'player'
of_game_stats = 'offense_game_stats'
df_game_stats = 'defense_game_stats'
st_game_stats = 'special_game_stats'
game_table = 'game'
stadium_table = 'stadium'
team_table = 'team'
season_table = 'season'
